server:
  port: 6969

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: geographics-service
          uri: lb://geographics-service
          predicates:
            - Path=/geographics/**
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/security/**
        - id: subnpay-service
          uri: lb://subnpay-service
          predicates:
            - Path=/subnpay/**
        - id: business-service
            uri: lb://business-service
            predicates:
              - Path=/business/**
